<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div id="shipping-plan">
    <div id="sku-lookup" data-bind="scope: 'skuLookup'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div id="box-configuration" data-bind="scope: 'boxConfiguration'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>


<script type="text/x-magento-init">
    {
        "#shipping-plan": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }

</script>
